config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  put "pages/register", to: "pages#register", as: "register"

end

app/models/lead.rb
class Lead < ActiveRecord::Base
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
require 'net/http'
require 'uri'
require 'json'

class PagesController < ApplicationController
  def home
    @lead = Lead.new
  end

  def register
    @lead = Lead.create(lead_params)
    respond_to do |format|
      if @lead.save
        payload = {
          username:         "New lead!",
          text:             @lead.name + " " + @lead.email + " " + @lead.business.to_s
        }
        uri = URI.parse("https://hooks.slack.com/services/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")
        Net::HTTP.post_form(uri, :payload => JSON.generate(payload))
        format.html { redirect_to root_path, notice: "Thanks! We'll get back to you soon." }
      else
        format.html { redirect_to root_path, alert: "Not registered. Have you entered a correct email?"}
      end
    end
  end

  def lead_params
    params.require(:lead).permit(:name, :email, :business)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- META TAGS -->
  <title>Meliorise, make yourself and the world better</title>
  <meta name="description" content="Discover Meliorise, the self-improvement coach with a motivation engine that lets you support causes you care for. Register now and get €5 free!">
  <meta property="og:image" content="http://s3.eu-central-1.amazonaws.com/meliorise/meliorise+self-improvement+logo.png">

  <!-- FAVICON -->
  <%= favicon_link_tag 'favicon.png' %>
  <%= csrf_meta_tags %>

  <!-- RESPONSIVITY -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- CSS -->
  <%= stylesheet_link_tag    'application', media: 'all' %>

  <!-- GOOGLE ANALYTICS -->


</head>

<body class='<%= "#{params[:controller]}-#{params[:action]}".gsub('_', '-') %>'>

  <!-- Has to be loaded first for the homepage effects -->
  <%= javascript_include_tag 'application' %>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <div class='site-content'>
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>

  <%= yield :javascript %>

</body>

</html>

app/views/pages/home.html.erb
<!-- FRONTLOADING OF NAVBAR JAVASCRIPT -->
<script type="text/javascript">
  $('.navbar-link').addClass("unscrolled")
  $('.navbar-button').addClass("unscrolled")
  $('.navicon').addClass("unscrolled")
  $('.navicon-small').addClass("unscrolled")
</script>

<!-- INTRO BANNER -->
<div class="banner" style="background-image: linear-gradient(-200deg, rgba(0,0,0,0.08) 5%, rgba(0,0,0,0.2) 90%), url(http://s3.eu-central-1.amazonaws.com/meliorise/selfimprovement-donation-banner4_small.jpeg);">
  <%= render 'pages/home/banner' %>
  <div class="scrollanchor" id="discover"></div>
</div>

<!-- DISCOVER -->
<div class="wrapper discover-section">
  <div style="position: relative;">
    <div class="text-center padded" >
      <div class="tagline""><h1>SELF-IMPROVEMENT, GENEROUSLY</h1></div>
      <%= render 'pages/home/discover' %>
    </div>
    <div style="position: absolute; bottom:70px;" id="howitworks"></div>
  </div>
</div>

<!-- HOW IT WORKS -->
<div class="how-it-works-section" style="position: relative">
  <div class="container padded timelinewrapper">
    <div class="tagline"><h1>MELIORISE REVEALS THE BETTER YOU</h1></div>
    <%= render 'pages/home/howitworks' %>
  </div>
  <div style="position: absolute; bottom:70px;" id="examples"></div>
</div>

<!-- EXAMPLES -->
<div class="examples-section" style="position: relative; background-image: linear-gradient(-200deg, rgba(0,0,0,0.1) 5%, rgba(0,0,0,0.4) 90%), url(http://s3.eu-central-1.amazonaws.com/meliorise/blurred-examples.jpg);">
  <div class="container padded">
    <div class="tagline"><h1>WHAT WILL BE YOUR STORY?</h1></div>
    <%= render 'pages/home/examples' %>
  </div>
  <div style="position: absolute; bottom:70px;" id="features"></div>
</div>

<!-- CALL TO ACTION -->
<div class="wrapper" id="testit">
  <div class="registerbox padded">
    <div class="tagline"><h1>JOIN NOW, BE IN THE KNOW</h1></div>
    <%= render 'pages/home/calltoaction' %>
  </div>
</div>

<!-- AFTERLOADING OF PAGE JAVASCRIPT -->
<% content_for :javascript do %>
<script>
  // Title dynamic resizing
  $("#headline").fitText(0.8, { minFontSize: '40px', maxFontSize: '70px' });
  $("#intro").fitText(1, { minFontSize: '10px', maxFontSize: '22px' });
  // Banner downarrow effects
  $("#scrollarrow").click(function() {
    $('html, body').animate({
      scrollTop: $("#discover").offset().top
    }, 1500);
  });
  function pulse(){
    if($(window).scrollTop() < 100) {
      $("#scrollarrow").animate({fontSize: "+=15"}, 700);
      $("#scrollarrow").animate({fontSize: "-=15"}, 700).delay(3000);
    }
  }
  setInterval(pulse, 3000);
</script>
<% end %>

app/views/pages/home/_banner.html.erb
<div class="banner-top"> </div>

<div class="banner-title text-center">
  <h1 id="headline">MAKE YOURSELF AND THE WORLD BETTER</h1>
</div>

<div class="banner-description">
  <p id="intro">Discover Meliorise, the self-improvement coach with a motivation engine that lets you support causes you care for</p>
</div>

<div class="banner-bottom">
  <div class="angle-down">
    <i class="fa fa-angle-down" id="scrollarrow"></i>
  </div>
</div>

app/views/pages/home/_calltoaction.html.erb
<div class="text-center" style="font-size: 18px;">At Meliorise, we believe every person has the potential to improve and get happier. We believe that happier individuals contribute to a better world as much as dedicated organizations, and that they can reward themselves for it!</div>
<br>
<div class="container">
  <div class='form text-center'>
    <%= simple_form_for @lead, :html => {:class => 'form-inline' }, url: register_path, method: :put do |f| %>
    <%= f.input :name, label: 'Name', input_html: { class: 'special' }  %>
    &nbsp;
    <%= f.input :email, :required => true, input_html: { class: 'special' }  %>
    &nbsp;
    <div>
      </br>
      <%= f.button :submit, 'JOIN!', :class=> "btn btn-primary" %>
    </div>
    <% end %>
  </div>
</div>

app/views/pages/home/_discover.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-4">
    <div class="feature-holder">
      <div class="feature">
        <%= image_tag("goodresolutions.png") %>
        <h2>TURN GOOD RESOLUTIONS INTO ACTIONS</h2>
        <p>Because just wishing is not enough, Meliorise helps you set, track, and reach meaningful personal objectives. It's a fact: what is measured, improves.</p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4">
    <div class="feature-holder">
      <div class="feature">
        <%= image_tag("incentivize.png") %>
        <h2>PUT A LITTLE STAKE IN THE GAME</h2>
        <p>It's easier to reach your objectives if you incentivize yourself. With Meliorise, lock an amount you'll retrieve at achievement, proportionally to your success.</p>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4">
    <div class="feature-holder">
      <div class="feature">
        <%= image_tag("betterworld.png") %>
        <h2>THE TWEAK FOR A BETTER WORLD</h2>
        <p>Here comes the tweak: the rest of the amount is donated to a nonprofit of your choice...so the world gets better anyway, through you or through them!</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/home/_examples.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-6">
    <div class="quote">
      <div class="content">
        With Meliorise, I managed to go exercise twice a week and stop using my smartphone when at the restaurant with friends, giving €30 to Médecins Sans Frontières in the process. Definitely worth it!"
        <br>
        <em>Eleanor</em>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6">
    <div class="quote">
      <div class="content">
        The app framed my attempt at spending more quality time with my kids, while helping me achieve a more eco-friendly diet. I donated €50 to WWF to celebrate this."
        <br>
        <em>Patrick</em>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-6">
    <div class="quote">
      <div class="content">
        I did not entirely manage my objective of spending less time on my computer in the evening...thus I donated €10 to Oxfam. I would have donated this amount anyway, even without the app: Meliorise just makes donating more fun!"
        <br>
        <em>Thomas</em>
      </div>
    </div>
  </div>
  <div class="col-xs-12 col-sm-6">
    <div class="quote">
      <div class="content">
      Thanks to the discipline that Meliorise provides, I successfully stopped eating junk food for at least 5 days a week. This way I got my full €25 incentive pledge back. I think I'll just reinvest that pledge in a new challenge!"
        <br>
        <em>Emily</em>
      </div>
    </div>
  </div>
</div>

app/views/pages/home/_howitworks.html.erb
 <section id="cd-timeline" class="cd-container">

  <div class="cd-timeline-block">
    <div class="cd-timeline-img cd-picture">
      <%= image_tag("set objectives.png") %>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
      <h2>SET OBJECTIVES AND MAKE A PLEDGE</h2>
      <p>Pick from a wide range of personal improvement points, or define your own. Set the timeline to reach them and lock an amount to incentivize yourself, as of €5 in one month</p>
    </div> <!-- cd-timeline-content -->
  </div> <!-- cd-timeline-block -->

  <div class="cd-timeline-block">
  <div class="cd-timeline-img cd-picture tracker">
      <%= image_tag "track objectives.png", :class => "playlogo" %>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
      <h2>TRACK YOUR ACHIEVEMENTS</h2>
      <p>Meliorise comes packed with coaching features so you stay on track to reach your objectives! Get reminders and tips & tricks to assess regularly where you stand</p>
    </div> <!-- cd-timeline-content -->
  </div> <!-- cd-timeline-block -->

  <div class="cd-timeline-block">
    <div class="cd-timeline-img cd-picture">
      <%= image_tag("partial success.png") %>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
      <h2>PARTIAL SUCCESS? NO BIG DEAL!</h2>
      <p>If you reach less than 100% of your objectives, then you retrieve that share of your pledge: the rest will be donated to a nonprofit of your choice, to make the world better anyway</p>
    </div> <!-- cd-timeline-content -->
  </div> <!-- cd-timeline-block -->

  <div class="cd-timeline-block">
    <div class="cd-timeline-img cd-picture">
      <%= image_tag("full success.png") %>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
      <h2>FULL SUCCESS IS YOURS TO CELEBRATE</h2>
      <p>Did you reach 100% of your objectives? Congrats! You'll get your full pledge back - with the opportunity to share it with a nonprofit, as a way to celebrate this achievement!</p>
    </div> <!-- cd-timeline-content -->
  </div> <!-- cd-timeline-block -->

</section> <!-- cd-timeline -->

app/views/pages/home/_timeline.html.erb
 <section id="cd-timeline" class="cd-container">

  <div class="cd-timeline-block">
    <div class="cd-timeline-img cd-picture">
      <%= image_tag("set objectives.png") %>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
      <h2>SET OBJECTIVES AND MAKE A PLEDGE</h2>
      <p>Choose from a wide range of personal improvement points, or define your own. Set the timeline to reach them and lock an amount to incentivize yourself, starting at €5 over one month</p>
    </div> <!-- cd-timeline-content -->
  </div> <!-- cd-timeline-block -->

  <div class="cd-timeline-block">
    <div class="cd-timeline-img cd-picture">
      <%= image_tag "track objectives.png", :class => "playlogo" %>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
      <h2>TRACK YOUR ACHIEVEMENTS</h2>
      <p>With Meliorise, check regularly where you stand. Get reminders and tips & tricks so you stay on track to reach your objectives</p>
    </div> <!-- cd-timeline-content -->
  </div> <!-- cd-timeline-block -->

  <div class="cd-timeline-block">
    <div class="cd-timeline-img cd-picture">
      <%= image_tag("partial success.png") %>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
      <h2>PARTIAL SUCCESS? NO BIG DEAL!</h2>
      <p>If you have reached less than 100% of your objectives, then you will retrieve that share of your pledge: the rest will be donated to a nonprofit of your choice, to make the world better anyway</p>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

    <div class="cd-timeline-block">
    <div class="cd-timeline-img cd-picture">
      <%= image_tag("full success.png") %>
    </div> <!-- cd-timeline-img -->

    <div class="cd-timeline-content">
      <h2>FULL SUCCESS IS YOURS TO CELEBRATE</h2>
      <p>Did you reach 100% of your objectives? Congrats! You'll get your full pledge back - with the opportunity to share it with a nonprofit, as a way to celebrate this achievement!</p>
      </div> <!-- cd-timeline-content -->
    </div> <!-- cd-timeline-block -->

  </section> <!-- cd-timeline -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class = "footerbox">
          <p>
            2016 Meliorise, all rights reserved
          </p>

          <p>
            A concept propelled by <%= link_to "Thomas Vanderstraeten", "http://be.linkedin.com/in/thomas-vanderstraeten-5710a148" %> in Brussels, BE
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="mynavbar navbar-fixed">
  <!-- Logo -->
  <%= link_to image_tag('logo.png'), root_path, id:"logo", class: "navbar-brand" %>

  <!-- Right Navigation, hidden on mobile -->
  <div class="navbar-right hidden-xs hidden-sm">

  <%= link_to "INTRO", "#", class: "navbar-item navbar-link"%>

    <%= link_to "DISCOVER", "#discover", class: "navbar-item navbar-link"%>

    <%= link_to "HOW IT WORKS", "#howitworks", class: "navbar-item navbar-link"%>

    <%= link_to "EXAMPLES", "#examples", class: "navbar-item navbar-link"%>

    <%= link_to "JOIN", "#testit", class: "navbar-item navbar-link" %>
  </div>
  <!-- end of right navigation -->

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-item hidden-md hidden-lg" style="display: flex; justify-content: space-around">
    <div class="dropdown">
      <i class="navicon fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-dropdown-menu">
        <li><%= link_to "INTRO", "#" %></li>
        <li><%= link_to "DISCOVER", "#discover" %></li>
        <li><%= link_to "HOW IT WORKS", "#howitworks" %></li>
        <li><%= link_to "EXAMPLES", "#examples" %></li>
        <li><%= link_to "JOIN", "#testit" %></li>
      </ul>
    </div>
  </div>
  <!-- end of mobile-only dropdown -->
</div>